### ISSUE TITLE
change glance distance to use tangents and not meters.

### ISSUE THREAD

**Issue by linas** [hansonrobotics/eva_behavior#39]
See the note on commit #38, copied below.

Rather than using the 3D distance, it would be much better to use the angular distance (x and y only). This is for several reasons: the z coordinate is very noisy, z is computed from the size of the face, and bounces around a lot (possibly by more than 1 meter). Next, if there are two people in view, and one is behind the other, they may be more than 1 meter apart, but since one is behind the other, they are very close visually.

It would be much better to measure the distance in tangents: that is, measure sqrt(xx+yy) / z -- that way, if two people are both far away, but the tangent is small, then she can glance between them. If they are close, but the tangent is large, then she cannot do this glancing.

**Comment by leungmanhin** [comment]
Yes agree, I'll created pull request #40 for this, please have a look, thanks.

**Comment by linas** [comment]
Thanks!
